const data = [
    {
      id: 1,
      title: 'Vegetable Biryani',
      category: 'Nandini Restaurant',
      price: 100.00,
      img: './images/Veg_Biryani.jpg',
      desc: ` A popular Indian rice dish made with aromatic basmati rice, flavorful spices, and a mixture of fresh vegetables. It is a hearty and nutritious meal that can be enjoyed on its own or served with raita and other side dishes. `,
      quantity: 0,
    },
    {
      id: 2,
      title: 'Bisibele Bath',
      category: 'Nagarjuna Restaurant',
      price: 50.00,
      img: './images/Bisibelebath.jpg',
      desc: `A traditional South Indian dish made with rice, lentils, and vegetables. Typically garnished with coconut and served with a side of raita, making it a complete and satisfying meal. `,
      quantity: 2,
    },
    {
      id: 3,
      title: 'Chicken Biryani',
      category: 'Anand Restaurant',
      price: 180.00,
      img: './images/Chicken_Biryani.jpg',
      desc: `It is made with tender pieces of chicken, aromatic basmati rice, and a mixture of spices. The dish is typically slow-cooked on low heat, allowing the flavors to blend and the chicken to cook to perfection. `,
      quantity: 0,
    },
    {
      id: 4,
      title: 'Idli & Vada',
      category: 'Nandini Restaurant',
      price: 40.00,
      img: './images/Idli_vada.jpg',
      desc: `Idlis are soft and fluffy steamed cakes made from a fermented batter of rice and black lentils, while Vadas are crispy deep-fried doughnuts made from the same batter. `,
      quantity: 0,
    },
    {
      id: 5,
      title: 'Chow Chow Path',
      category: 'Nagarjuna Restaurant',
      price: 65.00,
      img: './images/Chowchowpath.jpg',
      desc: `A South Indian dish made from leftover rice, vegetables, and spices. The ingredients are stir-fried together with spices, giving the dish a unique flavor and texture.`,
      quantity: 0,
    },
    {
      id: 6,
      title: 'Poori',
      category: 'Anand Restaurant',
      price: 70.00,
      img: './images/Poori.jpg',
      desc: `A popular Indian bread that is deep-fried and puffed up to create a light and crispy texture. Typically served with a variety of vegetarian dishes such as curries, chutneys, and lentil stews.`,
      quantity: 0
    },
    {
      id: 7,
      title: 'Masala Dosa',
      category: 'Nandini Restaurant',
      price: 60.00,
      img: './images/Masala_dosa.jpg',
      desc: `A popular South Indian dish made from a thin, crispy crepe filled with a spicy mixture of potatoes, onions, and spices. The crepe is made from a batter of rice and lentils and is fermented overnight to develop its signature flavor. `,
      quantity: 0,
    },
    {
      id: 8,
      title: 'South Indina Thali',
      category: 'Nagarjuna Restaurant',
      price: 180.00,
      img: './images/SouthIndia_Thali.jpg',
      desc: `A traditional platter that features a variety of South Indian dishes, served together on a single large plate. It is a complete and satisfying meal that showcases the diverse flavors and cooking styles of South India.`,
      quantity: 1,
    },
    {
      id: 9,
      title: 'North Indina Thali',
      category: 'Anand Restaurant',
      price: 200.00,
      img: './images/NorthIndian_Thali.jpg',
      desc: `A traditional platter that features a variety of North Indian dishes, served together on a single large plate. It is a complete and satisfying meal that showcases the diverse flavors and cooking styles of North India.`,
      quantity: 0,
    },
  ];
  export default data;
  